#!/usr/bin/env bash

# Suffix all lines from fd/0 with the content from fd/3 and print to fd/1.
#
# This is an example of a wrapper around a user program.

SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SUFFIX="$(head -n 1 /dev/fd/3)"

$SELF_DIR/suffix.rb "$SUFFIX"
